### ISSUE TITLE
Implement a command-line tool, which auto-attests claims

### ISSUE THREAD

**Issue by tjwelde** [KILTprotocol/demo-client#220]
This should be Node.js based and use the SDK
The user has to provide a ctype and a seed
The application listens to messages and auto-attests claims, if correct ctype

**Comment by LeonFLK** [comment]
Finished MVP 0.0.1

features subject to change:
Only runs once -> implement timeout parameter for loop
automatically attests claim for given ctypeHash regardless of content -> implement claimHashTree verifying
connects to demo client node wss://full-nodes.kilt.io:9944 -> implement node parameter to connect to

**Comment by LeonFLK** [comment]
Continuously running loop with async implementation and timeout parameter
