### ISSUE TITLE
Can not run  demo-client. No exporter memeber 'BaseConverter'

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [KILTprotocol/demo-client#221]
Hi,
I can not run demo-client. No matter if I am using docker or yarn commands. 

Error message: 

/app/node_modules/@types/bs58/index.d.ts
(7,10): Module '"../../base-x/src"' has no exported member 'BaseConverter'.

I am using newest Ubuntu. 
Npm version 6.9.0. 
Node version 12.6.0

**Comment by tjwelde** [comment]
Thank you for the bug report. The demo client is not really meant to be run by everyone, so we don't have a priority on maintaining it. You can use it @ https://demo.kilt.io though.
