### ISSUE TITLE
Tunnel public blockchain rpc ports

### ISSUE THREAD

**Issue by tjwelde** [KILTprotocol/demo-client#223]
So that the demo client works inside a restrictive firewall

**Comment by LeonFLK** [comment]
- the responsible security group would be load-balancer-fullnodes sg-0e0a66376876ef44b with 2 inbound rules 
    ```
    Custom TCP Rule | TCP | 9944 | 0.0.0.0/0
    Custom TCP Rule | TCP | 9944 | ::/0

    ```

- https://github.com/KILTprotocol/demo-client/blob/develop/.env has: 
    `REACT_APP_NODE_WS_PORT=9944`

    would need to change to 

    `REACT_APP_NODE_WS_PORT=443`

- would the docker image actually need to EXPOSE 443 in its Dockerfile or is that purely documentational?
    `EXPOSE 30333 9933 9944` (current state) to  `EXPOSE 30333 9933 9944 443

any additional dependencies that would need to be changed?

**Comment by tjwelde** [comment]
You don't need to change the docker image ports. But you have to find the actual corresponding loadbalancer and reconfigure it. They are liste in the EC2 service

**Comment by LeonFLK** [comment]
Things changed:

- .env.production changed `REACT_APP_NODE_WS_PORT=443`

- added 2 Custom TCP Rules to the security group sg-0e0a66376876ef44b:

    ```
    Custom TCP Rule | TCP | 443 | 0.0.0.0/0
    Custom TCP Rule | TCP | 443 | ::/0

    ```
- added Port 443 to listeners on `full-nodes-lb`
