### ISSUE TITLE
WSH - Don't prompt user to reset the client, after updating nodes

### ISSUE THREAD

**Issue by tjwelde** [KILTprotocol/demo-client#225]
Only prompt, if the chain was actually reset.
You can check this, by saving the current blocknumber every x seconds in localstorage and comparing the current blocknumber to the stored one

**Comment by LeonFLK** [comment]
awesome

**Comment by LeonFLK** [comment]
https://github.com/KILTprotocol/demo-client/blob/develop/src/services/ClientVersionHelper.ts has method checkVersion which checks if the Versions mismatch

change logic to updated check
