### ISSUE TITLE
Docker build errros

### ISSUE THREAD

**Issue by xz-cn** [KILTprotocol/demo-client#232]
Hello, I have a problem building the docker image.

Running `docker build -t kilt/prototype-client .` generated:

> ...
> ts-loader: Using typescript@3.7.2 and /app/tsconfig.prod.json
> Failed to compile.
> 
> /app/node_modules/@types/webassembly-js-api/index.d.ts
> (15,1): Definitions of the following identifiers conflict with those in another file: Imports, Exports, Module, Instance, Memory, Table, CompileError, LinkError, RuntimeError
> error Command failed with exit code 1.

This message `Definitions of the following identifiers conflict with those in another file` is really strange. Please have a check. Thank you.

**Comment by maudnals** [comment]
Thank you for the bug report! 
The demo client is not really meant to be run by everyone, we're purely using it for demo purposes. We're focusing on our SDK so we don't have a priority on maintaining the demo client.

If you'd like to see it in action: feel free to use the deployed version of it at  demo.kilt.io.
