### ISSUE TITLE
It doesn't work with mashnet-node@develop

### ISSUE THREAD

**Issue by qxiang88** [KILTprotocol/demo-client#278]
browser output like below:

<img width="1191" alt="2020-07-29 -00 55 35" src="https://user-images.githubusercontent.com/29155072/88697578-5f453900-d137-11ea-9b95-b1068db2e83d.png">

`2020-07-29 01:05:21        RPC-CORE: getMetadata (block: Hash): Metadata:: createType(Metadata):: U8a
: failed on 'MagicNumber':: U8a: failed on 'MetadataEnum':: Unable to create Enum via index 11, in V0
, V1, V2, V3, V4, V5, V6, V7, V8
2020-07-29 01:05:21   API/DECORATOR: Error: FATAL: Unable to initialize the API: getMetadata (block:
Hash): Metadata:: createType(Metadata):: U8a: failed on 'MagicNumber':: U8a: failed on 'MetadataEnum'
:: Unable to create Enum via index 11, in V0, V1, V2, V3, V4, V5, V6, V7, V8
`

**Comment by weichweich** [comment]
We are currently in the middle of updating to substrate 2.0.0. The mashnet-node is already updated but the demo-client is still work in progress.

You can track our work in [this PR](https://github.com/KILTprotocol/demo-client/pull/273).
